export const COUNTRY_OPTIONS = [
        "", "Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Antigua and Barbuda", "Argentina",
        "Armenia", "Australia", "Austria", "Azerbaijan", "Bahamas", "Bahrain", "Bangladesh", "Barbados",
        "Belarus", "Belgium", "Belize", "Benin", "Bhutan", "Bolivia", "Bosnia and Herzegovina", "Botswana",
        "Brazil", "Brunei", "Bulgaria", "Burkina Faso", "Burundi", "Cabo Verde", "Cambodia", "Cameroon",
        "Canada", "Central African Republic", "Chad", "Chile", "China", "Colombia", "Comoros", "Congo (Congo-Brazzaville)",
        "Costa Rica", "Croatia", "Cuba", "Cyprus", "Czech Republic", "Democratic Republic of the Congo", "Denmark",
        "Djibouti", "Dominica", "Dominican Republic", "Ecuador", "Egypt", "El Salvador", "Equatorial Guinea",
        "Eritrea", "Estonia", "Eswatini", "Ethiopia", "Fiji", "Finland", "France", "Gabon", "Gambia", "Georgia",
        "Germany", "Ghana", "Greece", "Grenada", "Guatemala", "Guinea", "Guinea-Bissau", "Guyana", "Haiti",
        "Honduras", "Hungary", "Iceland", "India", "Indonesia", "Iran", "Iraq", "Ireland", "Israel", "Italy",
        "Ivory Coast", "Jamaica", "Japan", "Jordan", "Kazakhstan", "Kenya", "Kiribati", "Kuwait", "Kyrgyzstan",
        "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein", "Lithuania", "Luxembourg",
        "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands", "Mauritania",
        "Mauritius", "Mexico", "Micronesia", "Moldova", "Monaco", "Mongolia", "Montenegro", "Morocco", "Mozambique",
        "Myanmar (Burma)", "Namibia", "Nauru", "Nepal", "Netherlands", "New Zealand", "Nicaragua", "Niger",
        "Nigeria", "North Korea", "North Macedonia", "Norway", "Oman", "Pakistan", "Palau", "Palestine State",
        "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines", "Poland", "Portugal", "Qatar", "Romania",
        "Russia", "Rwanda", "Saint Kitts and Nevis", "Saint Lucia", "Saint Vincent and the Grenadines", "Samoa",
        "San Marino", "Sao Tome and Principe", "Saudi Arabia", "Senegal", "Serbia", "Seychelles", "Sierra Leone",
        "Singapore", "Slovakia", "Slovenia", "Solomon Islands", "Somalia", "South Africa", "South Korea",
        "South Sudan", "Spain", "Sri Lanka", "Sudan", "Suriname", "Sweden", "Switzerland", "Syria", "Taiwan",
        "Tajikistan", "Tanzania", "Thailand", "Timor-Leste", "Togo", "Tonga", "Trinidad and Tobago", "Tunisia",
        "Turkey", "Turkmenistan", "Tuvalu", "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom",
        "United States of America", "Uruguay", "Uzbekistan", "Vanuatu", "Vatican City", "Venezuela", "Vietnam",
        "Yemen", "Zambia", "Zimbabwe"
    ];

export const DISCOUNT_OPTIONS =  [
        "Choose reason code",
        "Bank Charges",
        "Customs Duties",
        "Repair Costs",
        "Attorney Fees",
        "Taxes",
        "Late Delivery",
        "Freight Costs",
        "Reason Unknown",
        "Price Change",
        "Early payment allowance adjustment",
        "Quantity Discount",
        "Pricing Discount",
        "Volume Discount",
        "Agreed Discount",
        "Expediting fee",
        "Currency exchange differences"
    ];

export const OPTIONAL_FIELDS = {
        "": "Add optional field",
        "recurring": "Recurring",
        "discount": "Discount",
        "charge": "Charge (e.g. freight)",
        "bolid": "Transport Reference",
        "fileid": "File Id",
        "taxexemptionreason": "Tax exemption reason",
        "modelname": "Model name",
        "hsnsac": "HSN/SAC",
        "documentreference": "Purchase order number",
        "documentlinereference": "Purchase order line number",
        "accountingcost": "Cost center",
        "deliveryaddress": "Delivery Address",
        "actualdeliverydate": "Delivery Date",
        "buyersitemidentification": "Buyer material number",
        "origincountry": "Country of origin",
        "eccn": "Commodity classification: ECCN",
        "eangtin": "EAN/GTIN",
        "incoterms": "Delivery Terms",
        "manufacturename": "Manufacture name",
        "trackingid": "Freight order number",
        "serialID": "Serial number",
        "note": "Notes",
        "despatchlinedocumentreference": "Shipping Notice Reference",
        "despatchlineiddocumentreference": "Shipping Notice Line Reference",
        "receiptlinedocumentreference": "Goods Receipt Reference",
        "receiptlineiddocumentreference": "Goods Receipt Line Reference"
};

export const INVOICE_INFO_OPTIONAL_FIELDS = {
  "": "Add optional field",
  "DeliveryDate": "Delivery Date",
  "PaymentDueDate": "Payment Due Date",
  "customsDeclarations": "Customs Declarations",
  "taxExchangeRateFields": "Exchange rate",
  "transactionVatType": "Transaction VAT Type",
  "orderReferenceId": "Purchase order number",
  "orderReferenceIssueDate": "Purchase order issue date",
  "billingReferenceId": "Billing reference",
  "contractDocumentReferenceId": "Contract number",
  "despatchDocumentReference.id": "Shipping Notice Reference",
  "despatchDocumentReference.issueDate": "Shipping Notice Issue Date",
  "receiptDocumentReference.id": "Goods Receipt Reference",
  "receiptDocumentReference.issueDate": "Goods Receipt Issue Date",
  "accountingCost": "Cost center",
  "customerPartyContactName": "Person reference",
  "additionalReferences[BOL ID]": "Transport Reference",
  "BOLIssueDate": "Transport Reference Issue Date",
  "FileID": "File Id",
  "customerAssignedId": "Customer account ID",
  "taxPointDate": "Tax point date",
  "supplierCommissionNumber": "Commission number of seller",
  "supplierPhysicalLocationValue": "Data universal numbering system",
  "deliveryTerms": "Delivery Terms",
  "InternimHours": "Interim Hours",
  "BookingNumber": "Booking Number",
  "PaymentReference": "Payment Reference",
  "promisedDeliveryPeriod": "Delivery period",
  "ClearanceClave": "Clearance Clave"
};